import type { FeatureArea, ProductEventName } from "./events-product.ts";

const productEventFeatureAreas: Partial<Record<ProductEventName, FeatureArea>> = {
  attachment_delete_failed: "attachments",
  attachment_deleted: "attachments",
  attachment_opened: "attachments",
  attachment_upload_failed: "attachments",
  attachment_upload_started: "attachments",
  attachment_uploaded: "attachments",
  ideas_category_changed: "ideas",
  ideas_viewed: "ideas",
  public_share_view_changed: "sharing",
  public_share_viewed: "sharing",
  research_applied: "research",
  research_apply_failed: "research",
  research_apply_started: "research",
  research_create_failed: "research",
  research_create_started: "research",
  research_created: "research",
  research_delete_failed: "research",
  research_deleted: "research",
  research_revert_failed: "research",
  research_revert_started: "research",
  research_reverted: "research",
  research_update_failed: "research",
  research_updated: "research",
  route_calculated: "routes",
  route_calculation_failed: "routes",
  route_calculation_started: "routes",
  route_mode_changed: "routes",
  route_view_changed: "routes",
  share_export_failed: "sharing",
  share_export_started: "sharing",
  share_exported: "sharing",
  share_link_copied: "sharing",
  share_link_opened: "sharing",
  share_publish_failed: "sharing",
  share_publish_started: "sharing",
  share_published: "sharing",
  share_revoke_failed: "sharing",
  share_revoked: "sharing",
  share_settings_update_failed: "sharing",
  share_settings_updated: "sharing",
  variant_comparison_selection_changed: "variants",
  variant_comparison_summary_viewed: "variants",
  variant_comparison_viewed: "variants",
  variant_create_failed: "variants",
  variant_created: "variants",
  variant_delete_failed: "variants",
  variant_deleted: "variants",
  variant_primary_set: "variants",
  variant_primary_set_failed: "variants",
  variant_switched: "variants",
  variant_update_failed: "variants",
  variant_updated: "variants",
};

export function featureAreaForProductEvent(eventName: ProductEventName): FeatureArea | undefined {
  return productEventFeatureAreas[eventName];
}
