import type { PublicItinerary } from "@/features/sharing/types";

const ref = (value: string) => value.repeat(64);

export const parisPublicItinerary = {
  available: true,
  citySequence: [
    {
      date: "2027-04-12",
      dayNumber: 1,
      latitude: 48.8566,
      longitude: 2.3522,
      name: "Paris",
      ref: ref("a"),
    },
    {
      date: "2027-04-14",
      dayNumber: 3,
      latitude: 48.8014,
      longitude: 2.1301,
      name: "Versailles",
      ref: ref("b"),
    },
  ],
  days: [
    {
      city: "Paris",
      date: "2027-04-12",
      dayNumber: 1,
      items: [
        {
          place: { displayName: "Gare du Nord", localityName: "Paris" },
          ref: ref("c"),
          sortOrder: 1,
          startTime: "07:40",
          title: "Metro to hotel",
          transport: { destination: "Rive Gauche", origin: "Gare du Nord" },
          type: "transport",
        },
        {
          place: { displayName: "Marriott Rive Gauche", localityName: "Paris" },
          ref: ref("d"),
          sortOrder: 2,
          startTime: "09:00",
          title: "Marriott Rive Gauche",
          type: "hotel",
        },
        {
          place: { displayName: "Louvre Museum", localityName: "Paris" },
          ref: ref("e"),
          sortOrder: 3,
          startTime: "14:30",
          title: "Louvre Museum",
          type: "activity",
        },
        {
          place: { displayName: "Le Comptoir du Relais", localityName: "Paris" },
          ref: ref("f"),
          sortOrder: 4,
          startTime: "19:30",
          title: "Le Comptoir du Relais",
          type: "meal",
        },
      ],
      localities: ["Paris"],
      primaryLocality: "Paris",
      ref: ref("g"),
      title: "Arrival and the Left Bank",
    },
    {
      city: "Paris",
      date: "2027-04-13",
      dayNumber: 2,
      items: [
        {
          place: { displayName: "Musée de l’Orangerie", localityName: "Paris" },
          ref: ref("h"),
          sortOrder: 1,
          startTime: "10:00",
          title: "Musée de l’Orangerie",
          type: "activity",
        },
        {
          place: { displayName: "Canal Saint-Martin", localityName: "Paris" },
          ref: ref("i"),
          sortOrder: 2,
          startTime: "16:00",
          title: "Canal Saint-Martin walk",
          type: "activity",
        },
      ],
      localities: ["Paris"],
      primaryLocality: "Paris",
      ref: ref("j"),
      title: "Museums and the canal",
    },
    {
      city: "Versailles",
      date: "2027-04-14",
      dayNumber: 3,
      items: [
        {
          place: { displayName: "Palace of Versailles", localityName: "Versailles" },
          ref: ref("k"),
          sortOrder: 1,
          startTime: "09:30",
          title: "Palace of Versailles",
          type: "activity",
        },
        {
          place: { displayName: "Marché Notre-Dame", localityName: "Versailles" },
          ref: ref("l"),
          sortOrder: 2,
          startTime: "13:00",
          title: "Marché Notre-Dame",
          type: "meal",
        },
      ],
      localities: ["Versailles"],
      primaryLocality: "Versailles",
      ref: ref("m"),
      title: "Versailles day trip",
    },
  ],
  metadata: {
    coverCities: ["Paris", "Versailles"],
    description: "Four days across Paris and Versailles.",
    title: "Paris Trip",
  },
  savedRoutes: [],
  settings: {
    allowRouteExplore: false,
    defaultView: "overview",
    showAddresses: false,
    showAttachments: true,
    showMapRoutes: true,
    showNotes: true,
    showPlacePhotos: false,
    showQuickActionLinks: false,
    showTimes: true,
    templateId: "journal",
    templateVersion: 1,
  },
  trip: {
    dayCount: 4,
    endDate: "2027-04-15",
    startDate: "2027-04-12",
    timezone: "Europe/Paris",
    title: "Paris Trip",
  },
  variant: { color: "#78b79a", name: "Route A" },
} satisfies PublicItinerary;
