import type { PublicItinerary } from "@/features/sharing/types";

const ref = (value: string) => value.repeat(64);

export const sichuanPublicItinerary = {
  available: true,
  citySequence: [
    {
      date: "2027-10-02",
      dayNumber: 1,
      latitude: 30.05,
      longitude: 101.96,
      name: "Kangding",
      ref: ref("n"),
    },
    {
      date: "2027-10-03",
      dayNumber: 2,
      latitude: 30.04,
      longitude: 101.5,
      name: "Xinduqiao",
      ref: ref("o"),
    },
    {
      date: "2027-10-04",
      dayNumber: 3,
      latitude: 30.88,
      longitude: 101.89,
      name: "Danba",
      ref: ref("p"),
    },
  ],
  days: [
    {
      city: "Kangding",
      date: "2027-10-02",
      dayNumber: 1,
      items: [
        {
          place: { displayName: "Chengdu", localityName: "Chengdu" },
          ref: ref("q"),
          sortOrder: 1,
          startTime: "08:20",
          title: "Drive to Kangding",
          transport: { destination: "Kangding", origin: "Chengdu" },
          type: "transport",
        },
        {
          place: { displayName: "Xinduqiao Guesthouse", localityName: "Xinduqiao" },
          ref: ref("r"),
          sortOrder: 2,
          startTime: "14:00",
          title: "Xinduqiao Guesthouse",
          type: "hotel",
        },
        {
          place: { displayName: "Kangding Old Town", localityName: "Kangding" },
          ref: ref("s"),
          sortOrder: 3,
          startTime: "17:30",
          title: "Kangding Old Town",
          type: "activity",
        },
      ],
      localities: ["Kangding"],
      primaryLocality: "Kangding",
      ref: ref("t"),
      title: "Chengdu to the highlands",
    },
    {
      city: "Xinduqiao",
      date: "2027-10-03",
      dayNumber: 2,
      items: [
        {
          place: { displayName: "Tagong Grassland", localityName: "Tagong" },
          ref: ref("u"),
          sortOrder: 1,
          startTime: "10:30",
          title: "Tagong Grassland",
          type: "activity",
        },
        {
          place: { displayName: "Yak hotpot", localityName: "Xinduqiao" },
          ref: ref("v"),
          sortOrder: 2,
          startTime: "18:30",
          title: "Yak hotpot",
          type: "meal",
        },
      ],
      localities: ["Xinduqiao", "Tagong"],
      primaryLocality: "Xinduqiao",
      ref: ref("w"),
      title: "Grassland and mountain road",
    },
    {
      city: "Danba",
      date: "2027-10-04",
      dayNumber: 3,
      items: [
        {
          place: { displayName: "Jiaju Tibetan Village", localityName: "Danba" },
          ref: ref("x"),
          sortOrder: 1,
          startTime: "11:00",
          title: "Jiaju Tibetan Village",
          type: "activity",
        },
        {
          place: { displayName: "Danba Homestay", localityName: "Danba" },
          ref: ref("y"),
          sortOrder: 2,
          startTime: "16:00",
          title: "Danba Homestay",
          type: "hotel",
        },
      ],
      localities: ["Danba"],
      primaryLocality: "Danba",
      ref: ref("z"),
      title: "Village day in Danba",
    },
  ],
  metadata: {
    coverCities: ["Kangding", "Xinduqiao", "Danba"],
    description: "Four days across western Sichuan.",
    title: "Western Sichuan Loop",
  },
  savedRoutes: [],
  settings: {
    allowRouteExplore: false,
    defaultView: "overview",
    showAddresses: false,
    showAttachments: true,
    showMapRoutes: true,
    showNotes: true,
    showPlacePhotos: false,
    showQuickActionLinks: false,
    showTimes: true,
    templateId: "journal",
    templateVersion: 1,
  },
  trip: {
    dayCount: 4,
    endDate: "2027-10-05",
    startDate: "2027-10-02",
    timezone: "Asia/Shanghai",
    title: "Western Sichuan Loop",
  },
  variant: { color: "#78b79a", name: "Highland route" },
} satisfies PublicItinerary;
